### ISSUE TITLE
Task state-spaces different to original Fetch environments

### ISSUE THREAD

**Issue by RobertMcCarthy97** [IanYangChina/pybullet_multigoal_gym#2]
Firstly, thanks for the great open source environments! I was having lots of issues with the Mujoco licence so these are very useful.

I noticed that the state-spaces of these pmg tasks contain less information than those of the original Fetch tasks:

    [FetchReach-v1] state-space: Box(-inf, inf, (10,), float32)
    [FetchPush-v1] state-space: Box(-inf, inf, (25,), float32)
    [FetchSlide-v1] state-space: Box(-inf, inf, (25,), float32)
    [FetchPickAndPlace-v1] state-space: Box(-inf, inf, (25,), float32)
    
    [KukaReach] state-space: Box(-inf, inf, (3,), float32)
    [KukaPush] state-space: Box(-inf, inf, (20,), float32)
    [KukaSlide] state-space: Box(-inf, inf, (20,), float32)
    [KukaPickAndPlace] state-space: Box(-inf, inf, (20,), float32)

It seems in Reach the velocity of the gripper is missing, along with the relative distance of gripper to target.

It also appears that in object tasks the orientation of the object is [not being included](https://github.com/IanYangChina/pybullet_multigoal_gym/blob/6dcdff8e8b532fa4ba8c2c942107f37a8ec09f34/pybullet_multigoal_gym/envs/base_envs/kuka_single_step_base_env.py#L198).

I think including any missing info would be useful (i) to better replicate the original tasks and (ii) to ensure the environment is fully observable - missing information can make it more difficult to learn the task. For example, not knowing the orientation of the cube in Push makes the task more difficult and could possibly explain why *Bullet-DDPG-HER* performed worse than *Mujococ-DDPG-HER* in your [corresponding paper](https://arxiv.org/pdf/2105.05985.pdf)?

Anyway, let me know your thoughts/if I am mistaken about anything.

**Comment by IanYangChina** [comment]
> Firstly, thanks for the great open source environments! I was having lots of issues with the Mujoco licence so these are very useful.
> 
> I noticed that the state-spaces of these pmg tasks contain less information than those of the original Fetch tasks:
> 
> ```
> [FetchReach-v1] state-space: Box(-inf, inf, (10,), float32)
> [FetchPush-v1] state-space: Box(-inf, inf, (25,), float32)
> [FetchSlide-v1] state-space: Box(-inf, inf, (25,), float32)
> [FetchPickAndPlace-v1] state-space: Box(-inf, inf, (25,), float32)
> 
> [KukaReach] state-space: Box(-inf, inf, (3,), float32)
> [KukaPush] state-space: Box(-inf, inf, (20,), float32)
> [KukaSlide] state-space: Box(-inf, inf, (20,), float32)
> [KukaPickAndPlace] state-space: Box(-inf, inf, (20,), float32)
> ```
> 
> It seems in Reach the velocity of the gripper is missing, along with the relative distance of gripper to target.
> 
> It also appears that in object tasks the orientation of the object is [not being included](https://github.com/IanYangChina/pybullet_multigoal_gym/blob/6dcdff8e8b532fa4ba8c2c942107f37a8ec09f34/pybullet_multigoal_gym/envs/base_envs/kuka_single_step_base_env.py#L198).
> 
> I think including any missing info would be useful (i) to better replicate the original tasks and (ii) to ensure the environment is fully observable - missing information can make it more difficult to learn the task. For example, not knowing the orientation of the cube in Push makes the task more difficult and could possibly explain why _Bullet-DDPG-HER_ performed worse than _Mujococ-DDPG-HER_ in your [corresponding paper](https://arxiv.org/pdf/2105.05985.pdf)?
> 
> Anyway, let me know your thoughts/if I am mistaken about anything.

Hi, Robert

Thanks for raising up the questions :)
I'm aware of the differences between the state definitions of the original and my implementations.

I did it to some extend deliberately, because my PhD supervisor and I have come to the conclusion that some parts of the original state are redundant. 

For example, the velocity of the gripper is not absolute necessary for the Reach task, as the gripper is controlled with Position control mode (in both the mujoco and my implementation). This means at each MDP timestep, the gripper always has a near zero velocity. The original mujoco and the pmg both ensure this to happen by stepping multiple simulation steps within each MDP timestep, after any single MDP action has been passed to the simulation.

Secondly, the orientation of the object is included actually. If you look carefully [here](https://github.com/IanYangChina/pybullet_multigoal_gym/blob/6dcdff8e8b532fa4ba8c2c942107f37a8ec09f34/pybullet_multigoal_gym/envs/base_envs/kuka_single_step_base_env.py#L206), you can see the relative Euler orientation of the block with respect to the gripper tip frame. However, again, we decided to only provide the relative orientations simply because the absolute orientation can be inferred by it with the absolute gripper frame orientation. (By 'absolute' I mean in the robot base frame).

We have tested the PMG implementation with the exact same state definition in the original mujoco one, the performance did not have significant differences. We actually tested also the mujoco implementation with our new state definiton, it performs similarly as well. So my current suspects are laid on the differences between the physics engines themselves, or the robot arm differences. I have been trying to figure it out for quite a while, while I'm experimenting with the multi-step tasks. 

Anyway, thanks for the questions and feel free to do any modifications and tests based on your own hypotheses about what's going on in the simulation :) It would be even better if you can tell me your test results and theories about the underlying problems of the package.

**Comment by RobertMcCarthy97** [comment]
Thanks, that's good to know regarding the state definitions, it seems you've got everything covered!

I've only performed some preliminary experiments with the package atm but will let you know if I make any interesting discoveries.

**Comment by IanYangChina** [comment]
> Thanks, that's good to know regarding the state definitions, it seems you've got everything covered!
> 
> I've only performed some preliminary experiments with the package atm but will let you know if I make any interesting discoveries.

Yes please, play with it as you like :)
